name: caregiver_platform
description: Christy Cares - Caregiver Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  appwrite: ^13.0.0

  flutter_riverpod: ^2.5.1

  flutter_dotenv: ^5.1.0

  intl: ^0.19.0

  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env